name: Check pull request
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  DEBUG_DYN_ACTION_ENABLED: 'true'

jobs:
  ok_tests:
    name: "Run ok tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - &checkout_step
        name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          submodules: "recursive"
          ref: ${{ github.event.pull_request.head.sha }}
      - &setup_go
        name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26.x'
      - name: Run tests
        run: make makefile-go/test/ok/all

  fail_gitignore:
    name: "Run fail go/check/gitignore test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ok_tests]

    steps:
      - *checkout_step
      - name: Run test
        run: make makefile-go/test/fail/gitignore

  fail_lint:
    name: "Run fail go/lint test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ok_tests]

    steps:
      - *checkout_step
      - *setup_go
      - name: Run test
        run: make makefile-go/test/fail/lint

  fail_tidy:
    name: "Run fail go/check/no-tidy test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ok_tests]

    steps:
      - *checkout_step
      - *setup_go
      - name: Run test
        run: make makefile-go/test/fail/no-tidy

  fail_tests:
    name: "Run fail go/test test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ok_tests]

    steps:
      - *checkout_step
      - *setup_go
      - name: Run test
        run: make makefile-go/test/fail/run-tests

  action_tests_ok:
    name: "Test action test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ok_tests]

    steps:
      - *checkout_step
      - name: Setup
        uses: name212/action-dynamic-uses@f04c0fcc9dd6a60a7afc876e6c360b1ac9b5003c
        with:
          uses: 'dir:makefile-go/.github/actions/test'
          with: |
            go_version: "1.26.x"
            checkout: ""
            run_race_tests: "with_tests"
            parallel_tests: "false"
            test_tags: "test_tag_first,test_tag_second"
            envs: |
              # Pass event with comment
              BLAH_ENV=passed

